### ISSUE TITLE
'NeuroMLDocument' object has no attribute 'ion_channel_hhs'

### ISSUE THREAD

**Issue by rgerkin** [OpenSourceBrain/BlueBrainProjectShowcase#1]
When I do:  

```
python $OPENWORM_HOME/BlueBrainProjectShowcase/Channelpedia/NML2ChannelAnalyse.py -temperature 34   -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev -55  k_fast.channel.nml k_fast
```

with [this](https://github.com/openworm/muscle_model/blob/master/NeuroML2/k_fast.channel.nml) k_fast.channel.nml, I get this error:  

```
Traceback (most recent call last):
  File "/Users/rgerkin/Dropbox/dev/BlueBrainProjectShowcase/Channelpedia/NML2ChannelAnalyse.py", line 226, in <module>
    main()
  File "/Users/rgerkin/Dropbox/dev/BlueBrainProjectShowcase/Channelpedia/NML2ChannelAnalyse.py", line 191, in main
    for c in doc.ion_channel_hhs: 
AttributeError: 'NeuroMLDocument' object has no attribute 'ion_channel_hhs'
```

Inspection of the doc object shows only an 'ion_channels' attribute.  Are 'ion_channels_hhs' and 'ion_channel' deprecated in favor of 'ion_channels' or am I missing something?

**Comment by pgleeson** [comment]
Are you using the latest development branch of libNeuroML?

**Comment by rgerkin** [comment]
Looks like my pip installed version of libNeuroML was ahead of that one on my PYTHONPATH.  The instructions [here](https://github.com/openworm/muscle_model) should include an explicit adding of the checked out libNeuroML to the PYTHONPATH (otherwise they won't work, either because it would be on the PYTHONPATH, or because a rival version will be).  I'll make this suggestion over there.

**Comment by rgerkin** [comment]
Hmm, there is already a ```python setup.py install``` there.  I'm not sure what happened, in that case.
