### ISSUE TITLE
Error when opening model in Open Source Brain 3D explorer

### ISSUE THREAD

**Issue by wvangeit** [OpenSourceBrain/BlueBrainProjectShowcase#2]
When opening the Open Source Brain 3D explorer link in the README, and then click on 'Channels' in the explorer I get the error below. Similar issue for the 'Cell Info' button. 

http://opensourcebrain.org/projects/blue-brain-project-showcase/repository/revisions/master/show/NMC/NeuroML2?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FBlueBrainProjectShowcase%2Fmaster%2FNMC%2FNeuroML2%2FcADpyr232_L5_TTPC1_0fb1ca4724_0_0.cell.nml

Houston, we have a problem

Error populating the model tree for cADpyr232_L5_TTPC1_0fb1ca4724_0_0.electrical
Details

org.geppetto.core.common.GeppettoExecutionException: org.geppetto.core.common.GeppettoExecutionException: org.geppetto.core.model.ModelInterpreterException: org.geppetto.core.model.ModelInterpreterException: org.geppetto.core.model.ModelInterpreterException: org.geppetto.core.model.ModelInterpreterException: Cannot find the method setCondDensityin the NeuroML object Channel Density Nernst - axonal_gCa_HVAbar_Ca_HVA[[Ion Channel[[org.geppetto.core.model.runtime.TextMetadataNode@55a4a7e0, Anotation[[Description[[isDescribedBy[[org.geppetto.core.model.runtime.TextMetadataNode@2d098f0d, org.geppetto.core.model.runtime.TextMetadataNode@4e8eb594]], isVersionOf[[org.geppetto.core.model.runtime.TextMetadataNode@7b332fd6, org.geppetto.core.model.runtime.TextMetadataNode@5d89c9ca]]]]]], org.geppetto.core.model.runtime.TextMetadataNode@11f1cc0, Gate - m[[org.geppetto.core.model.runtime.TextMetadataNode@219881d3, Forward Rate[[HHExpLinearRate[[Dynamics[[org.geppetto.core.model.runtime.FunctionNode@237354e0]]]], org.geppetto.core.model.runtime.ParameterSpecificationNode@5ff92617, org.geppetto.core.model.runtime.ParameterSpecificationNode@5e33e13a, org.geppetto.core.model.runtime.ParameterSpecificationNode@2007d727]], Backward Rate[[HHExpRate[[Dynamics[[org.geppetto.core.model.runtime.FunctionNode@68c9504e]]]], org.geppetto.core.model.runtime.ParameterSpecificationNode@62be51de, org.geppetto.core.model.runtime.ParameterSpecificationNode@3cf0f877, org.geppetto.core.model.runtime.ParameterSpecificationNode@70486be2]], org.geppetto.core.model.runtime.TextMetadataNode@78b766a0, Type[[Dynamics[[org.geppetto.core.model.runtime.FunctionNode@50b2d04a, org.geppetto.core.model.runtime.FunctionNode@b88d3aa, org.geppetto.core.model.runtime.FunctionNode@440043d0]]]]]], Gate - h[[org.geppetto.core.model.runtime.TextMetadataNode@6d642f90, Forward Rate[[HHExpRate[[Dynamics[[org.geppetto.core.model.runtime.FunctionNode@4c6ecf0b]]]], org.geppetto.core.model.runtime.ParameterSpecificationNode@22a2fc05, org.geppetto.core.model.runtime.ParameterSpecificationNode@7a4fbe06, org.geppetto.core.model.runtime.ParameterSpecificationNode@944baa6]], Backward Rate[[HHSigmoidRate[[Dynamics[[org.geppetto.core.model.runtime.FunctionNode@7edb0260]]]], org.geppetto.core.model.runtime.ParameterSpecificationNode@7f39ed0a, org.geppetto.core.model.runtime.ParameterSpecificationNode@33f96cc7, org.geppetto.core.model.runtime.ParameterSpecificationNode@3c549779]], org.geppetto.core.model.runtime.TextMetadataNode@5c792db0, Type[[Dynamics[[org.geppetto.core.model.runtime.FunctionNode@17a6ad3e, org.geppetto.core.model.runtime.FunctionNode@3fb7cd93, org.geppetto.core.model.runtime.FunctionNode@3c198e93]]]]]], org.geppetto.core.model.runtime.ParameterSpecificationNode@31df73b8, org.geppetto.core.model.runtime.TextMetadataNode@45264e9c, IonChannelDynamics[[Dynamics[[org.geppetto.core.model.runtime.FunctionNode@55f3073b, org.geppetto.core.model.runtime.FunctionNode@465fde92]]]]]], org.geppetto.core.model.runtime.ParameterSpecificationNode@400d6756]]

**Comment by tarelli** [comment]
@wvangeit thanks for logging this, something for @adrianq to debug I think! Adrian let me know if I can be of any help.

**Comment by adrianq** [comment]
@wvangeit thanks! I will have a look at it and let you know...

**Comment by adrianq** [comment]
@wvangeit We have implemented a fix for this in Geppetto that went into the last release of Geppetto (thanks @tarelli for patching the release with this). I have just released the latest from Geppetto and OSB at opensourcebrain.org. It is working properly now. If you get any other error, let us know. Cheers!

**Comment by wvangeit** [comment]
Ok, great, that works.
Thanks.
